import type { CodegenConfig } from '@graphql-codegen/cli'

import { loadEnvConfig } from '@next/env'

loadEnvConfig(process.cwd())

const config: CodegenConfig = {
  schema: process.env.NEXT_PUBLIC_WORDPRESS_GRAPHQL_ENDPOINT,
  overwrite: true,
  documents: ['src/**/*.graphql', 'src/**/*.ts', 'src/**/*.tsx'],
  generates: {
    './src/graphql/generated/graphql.ts': {
      plugins: [
        {
          add: {
            content:
              '// @ts-nocheck\n// This file is auto-generated by GraphQL Code Generator. Do not edit.\n',
          },
        },
        'typescript-operations',
        'typed-document-node',
      ],
      config: {
        withHooks: true,
        withHOC: false,
        withComponent: false,
        extractAllFieldsToTypes: true,
        flattenGeneratedTypesIncludeFragments: true,
      },
    },
  },
}

export default config
