
import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import { MantineProvider } from "./providers/MantineProvider";
import "./globals.css";
import { ApolloProvider } from "./providers/ApolloProvider";
import '@mantine/core/styles.css';

const hankenGrotesk = Hanken_Grotesk({
  variable: "--hanken-grotesk-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable}  antialiased`}
      >
        <ApolloProvider>
          <MantineProvider>{children}</MantineProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
