import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import { MantineProvider } from "./providers/MantineProvider";
import "./globals.css";
import { ApolloWrapper } from "./providers/ApolloProvider";
import "@mantine/core/styles.css";

import { MENU_QUERY } from "@/graphql/queries/menu";
import { Get_MenuDocument, Get_MenuQuery } from "@/graphql/generated/graphql";
import { PreloadQuery } from "@/lib/apollo-client";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--hanken-grotesk-sans",
  subsets: ["latin"],
});

// 1. Defina a função para buscar os dados do menu no servidor

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hankenGrotesk.variable}  antialiased`}>
        <ApolloWrapper>
          {/* <PreloadQuery errorPolicy="ignore" fetchPolicy="cache-first"  query={Get_MenuDocument}> */}
            <MantineProvider>{children}</MantineProvider>
          {/* </PreloadQuery> */}
        </ApolloWrapper>
      </body>
    </html>
  );
}
